{
 "buildings": [
  {
   "id": "LIMCO II",
   "nombre": "LIMCO II",
   "torres": [
    "A",
    "B"
   ],
   "modulos": {
    "visitas": true,
    "visitas_recu": true,
    "hospedajes": false,
    "rondas": true,
    "propietarios": true,
    "residentes": true,
    "vehiculos": true,
    "incidentes": true,
    "encomiendas": true,
    "mantenimiento": true,
    "contactos": true,
    "normativas": true,
    "reportes": true
   }
  },
  {
   "id": "Millennial",
   "nombre": "Millennial",
   "torres": [],
   "modulos": {
    "visitas": true,
    "visitas_recu": false,
    "hospedajes": true,
    "rondas": true,
    "propietarios": true,
    "residentes": false,
    "vehiculos": true,
    "incidentes": true,
    "encomiendas": true,
    "mantenimiento": true,
    "contactos": true,
    "normativas": false,
    "reportes": true
   }
  }
 ],
 "propietarios": [
  {
   "id": "LIMCO-101A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "101A",
   "copropietario": "Milene Chavez",
   "telefono": "77096907",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "1",
   "vehiculo": "",
   "placa": "",
   "observaciones": "Ocupa el parqueo 60 debido a uan confuncion que se debe resolver lo que se tomara en cuenta es lo que dice los papeles de cada propietario"
  },
  {
   "id": "LIMCO-102A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "102A",
   "copropietario": "Yhanet Rojas",
   "telefono": "69029022",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "2",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-201A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "201A",
   "copropietario": "Roxana Chavez",
   "telefono": "77388873",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "4",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-202A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "202A",
   "copropietario": "Nancy Camacho",
   "telefono": "73603363",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "58",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-203A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "203A",
   "copropietario": "Shirley Balcazar",
   "telefono": "70897097",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "61",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-204A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "204A",
   "copropietario": "Veronica Aviles",
   "telefono": "71542948",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "62",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-301A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "301A",
   "copropietario": "",
   "telefono": "",
   "inquilino": "Mariela Ortiz",
   "telefono_inq": "67893444",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "26",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-302A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "302A",
   "copropietario": "Weng Zang",
   "telefono": "71333371",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "5",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-303A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "303A",
   "copropietario": "Silver Mancilla",
   "telefono": "71011496",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "6",
   "vehiculo": "Propietarios bloque A_Images/303A.VEHICULO.153134.jpg",
   "placa": "4420AUG",
   "observaciones": ""
  },
  {
   "id": "LIMCO-304A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "304A",
   "copropietario": "benigno Rodas",
   "telefono": "70740866",
   "inquilino": "Amalia Vargara",
   "telefono_inq": "779656405",
   "mascota": "Propietarios bloque A_Images/304A.MASCOTA.134817.jpg",
   "nombre_mascota": "Celeste y caramelo",
   "nro_parqueo": "7",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-401A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "401A",
   "copropietario": "Yamile Suarez",
   "telefono": "75008802",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "24",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-402A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "402A",
   "copropietario": "Jose Meyer",
   "telefono": "77382688",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "57",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-403A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "403A",
   "copropietario": "Eduardo Cortez",
   "telefono": "69289454",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "63",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-404A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "404A",
   "copropietario": "Carmen Landivar",
   "telefono": "78007466",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "10",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-501A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "501A",
   "copropietario": "Maria Esther Cossio",
   "telefono": "70944440",
   "inquilino": "Paula Añez",
   "telefono_inq": "76668107",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "11",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-502A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "502A",
   "copropietario": "Robert alarcon",
   "telefono": "67699260",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "12",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-503A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "503A",
   "copropietario": "Jorge Eduardo Roca",
   "telefono": "75002785",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "14",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-504A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "504A",
   "copropietario": "Ernesto Ribera",
   "telefono": "75565535",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "3",
   "vehiculo": "Propietarios bloque A_Images/504A.VEHICULO.162953.jpg",
   "placa": "5607GKL",
   "observaciones": "Gac gs4"
  },
  {
   "id": "LIMCO-601A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "601A",
   "copropietario": "katerine Paola Nieto",
   "telefono": "77060366",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "20",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-602A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "602A",
   "copropietario": "Jose Luis Rodriguez",
   "telefono": "71341542",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "602",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-603A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "603A",
   "copropietario": "Weng Zang",
   "telefono": "71333371",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "13",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-604A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "604A",
   "copropietario": "Caterine Illecas",
   "telefono": "69600732",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "17",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-701A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "701A",
   "copropietario": "Soraya Torrez",
   "telefono": "77096646",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "18",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-702A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "702A",
   "copropietario": "Mario Astroña",
   "telefono": "72422642",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "22",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-703A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "703A",
   "copropietario": "Edgar Revollo",
   "telefono": "78950269",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "59",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-704A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "704A",
   "copropietario": "Carlos Vigabriel",
   "telefono": "72100311",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "25,40,39",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-801A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "801A",
   "copropietario": "Henrry Barrios",
   "telefono": "73037635",
   "inquilino": "Roxana Navarro Romero",
   "telefono_inq": "69093520",
   "mascota": "Mirco Paredes Paz",
   "nombre_mascota": "Yareli Aponte",
   "nro_parqueo": "56",
   "vehiculo": "Lionel Bernal",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-802A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "802A",
   "copropietario": "Ariel Teran",
   "telefono": "75595967",
   "inquilino": "Nicol",
   "telefono_inq": "75074976",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "9",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-803A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "803A",
   "copropietario": "Alejandro Garcia",
   "telefono": "72621041",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "8",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-804A",
   "edificio": "LIMCO II",
   "torre": "A",
   "depto": "804A",
   "copropietario": "Luis Valdomar",
   "telefono": "79039369",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "23",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-101B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "101B",
   "copropietario": "Rubert Dantas",
   "telefono": "71315415",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "15",
   "vehiculo": "Propietarios bloque B_Images/101B.VEHICULO.141345.jpg",
   "placa": "5723KAX",
   "observaciones": ""
  },
  {
   "id": "LIMCO-102B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "102B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "Kalia Argandoña",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "46",
   "vehiculo": "Propietarios bloque B_Images/102B.VEHICULO.133303.jpg",
   "placa": "5166RNX",
   "observaciones": "MITSUBISHI MIRAGE G4"
  },
  {
   "id": "LIMCO-201B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "201B",
   "copropietario": "Fabiola Asbun",
   "telefono": "75504396",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "27",
   "vehiculo": "Propietarios bloque B_Images/201B.VEHICULO.135541.jpg",
   "placa": "5650PNY",
   "observaciones": "El parqueo 27 lo alquila el 501-B /  VOLKSWAGUEN  GOL"
  },
  {
   "id": "LIMCO-202B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "202B",
   "copropietario": "Isaac Limpias",
   "telefono": "",
   "inquilino": "Vladimir Valdez",
   "telefono_inq": "71681774",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "16",
   "vehiculo": "Propietarios bloque B_Images/202B.VEHICULO.141416.jpg",
   "placa": "1479SGA",
   "observaciones": "El parqueo 16 lo alquila el 204-A"
  },
  {
   "id": "LIMCO-203B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "203B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "Rodrigo Claros",
   "telefono_inq": "75302048",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "32",
   "vehiculo": "Propietarios bloque B_Images/203B.VEHICULO.140135.jpg",
   "placa": "6435IKB",
   "observaciones": "SUZUKI DEZIRE"
  },
  {
   "id": "LIMCO-204B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "204B",
   "copropietario": "Yuli Medina",
   "telefono": "75610053",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "29",
   "vehiculo": "Propietarios bloque B_Images/204B.VEHICULO.150248.jpg",
   "placa": "4779ZDI",
   "observaciones": ""
  },
  {
   "id": "LIMCO-301B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "301B",
   "copropietario": "Margot Aguilera",
   "telefono": "49",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "49",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-302B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "302B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "53",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-303B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "303B",
   "copropietario": "Karla Dabdoub",
   "telefono": "750001019",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "41",
   "vehiculo": "Propietarios bloque B_Images/303B.VEHICULO.132623.jpg",
   "placa": "4747YDE",
   "observaciones": "Nissan kicks"
  },
  {
   "id": "LIMCO-304B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "304B",
   "copropietario": "Rolando Roca",
   "telefono": "75003931",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "51",
   "vehiculo": "Propietarios bloque B_Images/304B.VEHICULO.133015.jpg",
   "placa": "3113DPY",
   "observaciones": "ZOTYE HUNTER"
  },
  {
   "id": "LIMCO-401B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "401B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "50",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-402B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "402B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "44",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-403B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "403B",
   "copropietario": "Ricardo vaca",
   "telefono": "78400082",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "55-54",
   "vehiculo": "Propietarios bloque B_Images/403B.VEHICULO.150708.jpg",
   "placa": "5317YCB",
   "observaciones": "Tienen un SUZUKI DESZIRE GRIS / placa"
  },
  {
   "id": "LIMCO-404B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "404B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "43",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-501B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "501B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "31",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-502B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "502B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "45",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-503B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "503B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "38",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-504B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "504B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "37",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-601B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "601B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "48",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-602B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "602B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "30",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-603B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "603B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "19",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-604B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "604B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "34",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-701B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "701B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "47",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-702B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "702B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "28",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-703B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "703B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "36",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-704B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "704B",
   "copropietario": "Luciana marin",
   "telefono": "70061055",
   "inquilino": "David",
   "telefono_inq": "60019118",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "35",
   "vehiculo": "Propietarios bloque B_Images/704B.VEHICULO.151036.jpg",
   "placa": "",
   "observaciones": "El vehículo motorizado es del inquilino David"
  },
  {
   "id": "LIMCO-801B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "801B",
   "copropietario": "Horacio Avila",
   "telefono": "21",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "21",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-802B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "802B",
   "copropietario": "Albricia añez",
   "telefono": "33",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "33",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-803B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "803B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "52",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "LIMCO-804B",
   "edificio": "LIMCO II",
   "torre": "B",
   "depto": "804B",
   "copropietario": "",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "42",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-21-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "21",
   "copropietario": "Bladimir Honor",
   "telefono": "77333264",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-21-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "21",
   "copropietario": "Marbel Roxana Galean Barriga",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-22-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "22",
   "copropietario": "Edwin Mario Santa Cruz Álvarez",
   "telefono": "75261090",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-23-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "23",
   "copropietario": "Oscar Mario Rivero",
   "telefono": "76663090",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-24-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "24",
   "copropietario": "Oscar Mario Rivero (P-12)",
   "telefono": "76663090",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-25-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "25",
   "copropietario": "Rocio Solares Palma",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-25-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "25",
   "copropietario": "Luis Camargo",
   "telefono": "77895612",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-26-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "26",
   "copropietario": "Waldo Danilo Pereira Vargas",
   "telefono": "77078178",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-31-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "31",
   "copropietario": "Liliana Beatriz Arteaga Zapata",
   "telefono": "77350850",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-32-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "32",
   "copropietario": "Liliana Beatriz Arteaga Zapata",
   "telefono": "77350850",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-33-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "33",
   "copropietario": "Guillermo Sotomayor (P-S)",
   "telefono": "76340880",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-34-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "34",
   "copropietario": "Gualberto Guerrero Postigo",
   "telefono": "72117255",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-35-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "35",
   "copropietario": "Cesar Fernando Zelaya Arias (P-10)",
   "telefono": "77622273",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-36-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "36",
   "copropietario": "Ricarda Torrico Soliz",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-36-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "36",
   "copropietario": "Luis Antezana",
   "telefono": "77214704",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-41-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "41",
   "copropietario": "Yurisa Andrea Agramont Carrillo",
   "telefono": "72057389",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-42-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "42",
   "copropietario": "Yurisa Andrea Agramont Carrillo",
   "telefono": "72057389",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-43-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "43",
   "copropietario": "Gabriel Melgares Camacho",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-44-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "44",
   "copropietario": "Livia Puga Hamude",
   "telefono": "77806565",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-45-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "45",
   "copropietario": "Margoth Sosa Oliva",
   "telefono": "70017072",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-46-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "46",
   "copropietario": "Eduardo Danilo Aliaga Venegas",
   "telefono": "70139697",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-51-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "51",
   "copropietario": "Claudia Julieta Bengolea Zeballos",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-51-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "51",
   "copropietario": "Nadia",
   "telefono": "75352783",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-52-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "52",
   "copropietario": "Valeria Vasquez Zabala",
   "telefono": "78181285",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-53-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "53",
   "copropietario": "Gloria Shirley Gonzalez Ruiz",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-53-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "53",
   "copropietario": "Mariana Alarcón",
   "telefono": "13348706362",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-54-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "54",
   "copropietario": "Marcio Alvarez Rocha",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-54-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "54",
   "copropietario": "Gabriela Moreno",
   "telefono": "78509793",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-55-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "55",
   "copropietario": "Elena Sarmiento",
   "telefono": "78550855",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-56-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "56",
   "copropietario": "Heidy Bauer Salas",
   "telefono": "71053683",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-61-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "61",
   "copropietario": "Rodrigo Guillen Loaiza",
   "telefono": "71622214",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-62-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "62",
   "copropietario": "Ricardo David Rivera",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-63-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "63",
   "copropietario": "Tania Jazmín Pereyra Menacho",
   "telefono": "77083029",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-64-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "64",
   "copropietario": "Josefina Ribera Vaca (P-6)",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-64-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "64",
   "copropietario": "Ricardo Rojas",
   "telefono": "77319148",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-65-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "65",
   "copropietario": "Julia Teresa Hoffmann de Roca",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-66-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "66",
   "copropietario": "Michelle Koester Dorado",
   "telefono": "75386421",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-71-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "71",
   "copropietario": "Gabriela Salas Echeverry",
   "telefono": "75001504",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-72-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "72",
   "copropietario": "Stephanie Sandoval",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-73-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "73",
   "copropietario": "Yannine Balcazar",
   "telefono": "68923009",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-74-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "74",
   "copropietario": "María Alejandra Rojas Rosado",
   "telefono": "69283878",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-75-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "75",
   "copropietario": "Nelda Isabel Añez Mustafá",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-75-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "75",
   "copropietario": "Stefanny Galindo",
   "telefono": "77820900",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-76-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "76",
   "copropietario": "Valeria Rodríguez Subirana",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-76-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "76",
   "copropietario": "Yenia Subirana",
   "telefono": "78181290",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-81-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "81",
   "copropietario": "Renato Carlos Loayza Blanco",
   "telefono": "72270200",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-82-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "82",
   "copropietario": "Estefani Yabeta Cuellar",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-82-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "82",
   "copropietario": "Laura Ríos",
   "telefono": "79375493",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-83-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "83",
   "copropietario": "Paola Bernardina Salguero",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-84-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "84",
   "copropietario": "Wilson Lozada",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-84-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "84",
   "copropietario": "Matías Lozano",
   "telefono": "77397050",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-85-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "85",
   "copropietario": "María Daniela Justiniano Fernández",
   "telefono": "77393540",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-86-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "86",
   "copropietario": "Taina Cortéz Antunez",
   "telefono": "77030270",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-91-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "91",
   "copropietario": "Dagner Rome Rivero Zimmermann",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-91-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "91",
   "copropietario": "Nicolás Rivero",
   "telefono": "76621858",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-92-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "92",
   "copropietario": "Maria del Carmen Paz (G13)",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-92-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "92",
   "copropietario": "Carmiña Paz",
   "telefono": "77355666",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-93-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "93",
   "copropietario": "Grover Castro Gordillo",
   "telefono": "72043434",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-94-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "94",
   "copropietario": "Oscar Mario Landivar",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-94-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "94",
   "copropietario": "Valentina Celins",
   "telefono": "72556949",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-95-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "95",
   "copropietario": "Rodny Chalar Valverde",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-96-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "96",
   "copropietario": "Rosa Rossel Villalobos",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-101-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "101",
   "copropietario": "Roberto Joao de Oliveira",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-101-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "101",
   "copropietario": "Fátima Elva Gómez Gallo",
   "telefono": "77007157",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-102-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "102",
   "copropietario": "Ingrid Micaela Candia Scholz",
   "telefono": "70611374",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-103-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "103",
   "copropietario": "José Guillermo Prudencio Pinto",
   "telefono": "69098300",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-104-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "104",
   "copropietario": "Rubén Martínez Ortega",
   "telefono": "72422084",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-105-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "105",
   "copropietario": "Hugo Vaca Martínez",
   "telefono": "71334499",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-106-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "106",
   "copropietario": "Santiago Enrique Suarez Montenegro",
   "telefono": "",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-106-1",
   "edificio": "Millennial",
   "torre": "",
   "depto": "106",
   "copropietario": "Paola Montenegro",
   "telefono": "34603115001",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-111-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "111",
   "copropietario": "Marcio Álvarez Rocha",
   "telefono": "78413184",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  },
  {
   "id": "MILL-112-0",
   "edificio": "Millennial",
   "torre": "",
   "depto": "112",
   "copropietario": "Patricia Villagómez Paredes",
   "telefono": "72150502",
   "inquilino": "",
   "telefono_inq": "",
   "mascota": "",
   "nombre_mascota": "",
   "nro_parqueo": "",
   "vehiculo": "",
   "placa": "",
   "observaciones": ""
  }
 ],
 "residentes": [
  {
   "edificio": "LIMCO II",
   "depto": "303A",
   "nombre": "Rocio",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "304A",
   "nombre": "Roxana Peñaranda",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "101B",
   "nombre": "Dilia callaú",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "101B",
   "nombre": "Señora mercedes - personal de servicios",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "102B",
   "nombre": "Nahomi Argandoña",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "102B",
   "nombre": "Valeria Argandoña",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "102B",
   "nombre": "Señora Frida - Adulta mayor",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "201B",
   "nombre": "DEPARTAMENTO VACÍO",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "201B",
   "nombre": "DEPARTAMENTO VACÍO",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "202B",
   "nombre": "Jeaacarla Subirana",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "202B",
   "nombre": "Ninfa Saldias",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "203B",
   "nombre": "Mónica Medina",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "203B",
   "nombre": "Santiago Claros",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "204B",
   "nombre": "Carlos Rojas",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "204B",
   "nombre": "Karenina Rojas",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "204B",
   "nombre": "Nataly Rojas",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "204B",
   "nombre": "Rene Ayala",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "204B",
   "nombre": "Thiago Ayala",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "303B",
   "nombre": "Nicolás",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "304B",
   "nombre": "Señora Maria",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "304B",
   "nombre": "Santiago Roca",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "403B",
   "nombre": "Mayerly Gómez",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "403B",
   "nombre": "Tienen 3 niñitas",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "403B",
   "nombre": "Diana",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "403B",
   "nombre": "Diane",
   "parentesco": "",
   "celular": ""
  },
  {
   "edificio": "LIMCO II",
   "depto": "603B",
   "nombre": "Jose Carlos",
   "parentesco": "",
   "celular": ""
  }
 ],
 "vehiculos": [
  {
   "edificio": "LIMCO II",
   "depto": "303A",
   "placa": "4420AUG",
   "vehiculo": "Propietarios bloque A_Images/303A.VEHICULO.153134.jpg",
   "propietario": "Silver Mancilla",
   "nro_parqueo": "6"
  },
  {
   "edificio": "LIMCO II",
   "depto": "504A",
   "placa": "5607GKL",
   "vehiculo": "Propietarios bloque A_Images/504A.VEHICULO.162953.jpg",
   "propietario": "Ernesto Ribera",
   "nro_parqueo": "3"
  },
  {
   "edificio": "LIMCO II",
   "depto": "101B",
   "placa": "5723KAX",
   "vehiculo": "Propietarios bloque B_Images/101B.VEHICULO.141345.jpg",
   "propietario": "Rubert Dantas",
   "nro_parqueo": "15"
  },
  {
   "edificio": "LIMCO II",
   "depto": "102B",
   "placa": "5166RNX",
   "vehiculo": "Propietarios bloque B_Images/102B.VEHICULO.133303.jpg",
   "propietario": "",
   "nro_parqueo": "46"
  },
  {
   "edificio": "LIMCO II",
   "depto": "201B",
   "placa": "5650PNY",
   "vehiculo": "Propietarios bloque B_Images/201B.VEHICULO.135541.jpg",
   "propietario": "Fabiola Asbun",
   "nro_parqueo": "27"
  },
  {
   "edificio": "LIMCO II",
   "depto": "202B",
   "placa": "1479SGA",
   "vehiculo": "Propietarios bloque B_Images/202B.VEHICULO.141416.jpg",
   "propietario": "Isaac Limpias",
   "nro_parqueo": "16"
  },
  {
   "edificio": "LIMCO II",
   "depto": "203B",
   "placa": "6435IKB",
   "vehiculo": "Propietarios bloque B_Images/203B.VEHICULO.140135.jpg",
   "propietario": "",
   "nro_parqueo": "32"
  },
  {
   "edificio": "LIMCO II",
   "depto": "204B",
   "placa": "4779ZDI",
   "vehiculo": "Propietarios bloque B_Images/204B.VEHICULO.150248.jpg",
   "propietario": "Yuli Medina",
   "nro_parqueo": "29"
  },
  {
   "edificio": "LIMCO II",
   "depto": "303B",
   "placa": "4747YDE",
   "vehiculo": "Propietarios bloque B_Images/303B.VEHICULO.132623.jpg",
   "propietario": "Karla Dabdoub",
   "nro_parqueo": "41"
  },
  {
   "edificio": "LIMCO II",
   "depto": "304B",
   "placa": "3113DPY",
   "vehiculo": "Propietarios bloque B_Images/304B.VEHICULO.133015.jpg",
   "propietario": "Rolando Roca",
   "nro_parqueo": "51"
  },
  {
   "edificio": "LIMCO II",
   "depto": "403B",
   "placa": "5317YCB",
   "vehiculo": "Propietarios bloque B_Images/403B.VEHICULO.150708.jpg",
   "propietario": "Ricardo vaca",
   "nro_parqueo": "55-54"
  }
 ],
 "contactos": [
  {
   "edificio": "LIMCO II",
   "nombre": "Villa Santa",
   "telefono": "69150144"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "Policia",
   "telefono": "110"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "Ambulancias",
   "telefono": "160"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "Cruz",
   "telefono": "3331965"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "Transito",
   "telefono": "114"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "Diprove",
   "telefono": "115"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "C.R.E",
   "telefono": "176"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "SAGUAPAC",
   "telefono": "178"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "SAN JUAN DE DIOS HOSPITAL",
   "telefono": "118"
  },
  {
   "edificio": "Millennial",
   "nombre": "SEGURIDAD OSIRIS - 71680781",
   "telefono": "78086408"
  },
  {
   "edificio": "Millennial",
   "nombre": "Farmamóvil - 777 55555",
   "telefono": "77755555"
  },
  {
   "edificio": "Millennial",
   "nombre": "CRE - 176",
   "telefono": "176"
  },
  {
   "edificio": "Millennial",
   "nombre": "SAGUAPAC - 178",
   "telefono": "178"
  },
  {
   "edificio": "Millennial",
   "nombre": "SISME-EMERGENCIAS MEDICAS - 160",
   "telefono": "160"
  },
  {
   "edificio": "Millennial",
   "nombre": "BOMBEROS VOLUNTARIOS - 123",
   "telefono": "123"
  },
  {
   "edificio": "Millennial",
   "nombre": "BOMBEROS POLICIA - 119",
   "telefono": "119"
  },
  {
   "edificio": "Millennial",
   "nombre": "BOMBEROS FUNDASOL - 800124000",
   "telefono": "800124000"
  },
  {
   "edificio": "Millennial",
   "nombre": "CRUZ ROJA - 33331965",
   "telefono": "33331965"
  },
  {
   "edificio": "Millennial",
   "nombre": "CAJA PETROLERA DE SALUD - 33339119",
   "telefono": "33339119"
  },
  {
   "edificio": "Millennial",
   "nombre": "HOSPITAL SAN JUAN DE DIOS - 118",
   "telefono": "118"
  },
  {
   "edificio": "Millennial",
   "nombre": "SEDES - 33332770",
   "telefono": "33332770"
  },
  {
   "edificio": "Millennial",
   "nombre": "RADIO PATRULLA - 110",
   "telefono": "110"
  },
  {
   "edificio": "Millennial",
   "nombre": "TRANSITO - 114",
   "telefono": "114"
  },
  {
   "edificio": "Millennial",
   "nombre": "DIPROVE - 115",
   "telefono": "115"
  }
 ],
 "normativas": [
  {
   "edificio": "LIMCO II",
   "nombre": "REGLAMENTO INTERNO"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "ALQUILER DE AREAS SOCIALES"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "LEY DE PROPIEDAD HORIZONTAL"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "QR DEL EDIFICIO"
  },
  {
   "edificio": "LIMCO II",
   "nombre": "Mapa de Parqueos"
  }
 ]
}