-- ============================================================
-- OSIRIS - Tablas en la nube (Supabase)  ·  v2 (arregla RLS 42501)
-- Pega TODO esto en Supabase -> SQL Editor -> New query -> Run
-- ============================================================

-- 1) Tablas (si no existen)
create table if not exists eventos (
  id bigint generated by default as identity primary key,
  tipo text,
  edificio text,
  guardia text,
  detalle jsonb default '{}'::jsonb,
  device_id text,
  created_at timestamptz default now()
);

create table if not exists presencia (
  device_id text primary key,
  guardia text,
  edificio text,
  en_turno boolean default false,
  last_seen timestamptz default now()
);

-- 2) Permisos para la clave publica (rol anon)
grant usage on schema public to anon;
grant select, insert, update, delete on eventos to anon;
grant select, insert, update, delete on presencia to anon;
grant usage, select on all sequences in schema public to anon;

-- 3) RLS ACTIVO pero con politica permisiva para anon (esto arregla el error
--    "new row violates row-level security policy ... code 42501").
alter table eventos enable row level security;
drop policy if exists osiris_eventos_all on eventos;
create policy osiris_eventos_all
  on eventos for all
  to anon, authenticated
  using (true)
  with check (true);

alter table presencia enable row level security;
drop policy if exists osiris_presencia_all on presencia;
create policy osiris_presencia_all
  on presencia for all
  to anon, authenticated
  using (true)
  with check (true);
