-- ============================================================
-- CondoControl Pro - Tablas en la nube (Supabase)
-- Pega TODO esto en Supabase → SQL Editor → New query → Run
-- ============================================================

create table if not exists eventos (
  id bigint generated by default as identity primary key,
  tipo text,
  edificio text,
  guardia text,
  detalle jsonb default '{}'::jsonb,
  device_id text,
  created_at timestamptz default now()
);

create table if not exists presencia (
  device_id text primary key,
  guardia text,
  edificio text,
  en_turno boolean default false,
  last_seen timestamptz default now()
);

-- Para esta primera version dejamos las tablas sin RLS (candado por fila),
-- asi la app funciona de inmediato con la clave publishable.
alter table eventos disable row level security;
alter table presencia disable row level security;

-- Damos permisos a la clave publica (anon) para leer y escribir.
grant select, insert, update on eventos to anon;
grant select, insert, update on presencia to anon;
grant usage, select on sequence eventos_id_seq to anon;
